### ISSUE TITLE
Can't update from GitLab package repository

### ISSUE THREAD

**Issue by AlixBa** [rtimush/sbt-updates#241]
Hey,

sbt-updates does not work for GitLab private package repository.
GitLab expects a header "Private-Token: <token>" or "Job-Token: <token>".

Currently, the plugin sends a "Authorization: Basic b64(Private-Token:<token>)".
Could it be possible to send, raw, a header "user: password" or is it sensitive?
Is there another way?

It seems that Coursier does this when `csrConfiguration ~= (_.addRepositoryAuthentication(_realm, auth)),`
```
  "authorization": "Basic Og==",
  "private-token": "<token>",
```

**Comment by rtimush** [comment]
Should be fixed in `0.6.1-16-3dabeef-SNAPSHOT`. It would be really nice if someone using a private GitLab package repository can try it and confirm that `sbt-updates` now correctly picks up authentication headers from the `csrConfiguration` setting.

**Comment by AlixBa** [comment]
Mmm I quickly tested and I'm not sure it's working. I'll have a closer look soon.

**Comment by AlixBa** [comment]
So here is my conf
```scala
lazy val gitlabMavenSettings: Seq[Def.Setting[_]] = {
  val file = Path.userHome / ".sbt" / "credentials" / "gitlab-maven"
  val creds: Vector[(String, String)] = Vector(
    Some(file).filter(_.exists()).map { file =>
      val direct = toDirect(Credentials(file))
      (direct.userName, direct.passwd)
    },
    Some(("Deploy-Token", sys.env.getOrElse("REGISTRY_TOKEN", "")))
      .filter(_ => sys.env.contains("REGISTRY_TOKEN")),
    Some(("Job-Token", sys.env.getOrElse("CI_JOB_TOKEN", "")))
      .filter(_ => sys.env.contains("CI_JOB_TOKEN"))
  ).flatten

  val auth = Authentication(creds)

  Seq(
    resolvers ++= Seq(
      "gitlab-maven-1" at "https://gitlab.com/api/v4/projects/XXX/packages/maven",
      "gitlab-maven-2" at "https://gitlab.com/api/v4/projects/YYY/packages/maven",
      "gitlab-maven-3" at "https://gitlab.com/api/v4/projects/ZZZ/packages/maven"
    ),
    credentials ++= creds.flatMap { case (username, password) =>
      List(
        new DirectCredentials("gitlab-maven-1", "gitlab.com", username, password),
        new DirectCredentials("gitlab-maven-2", "gitlab.com", username, password),
        new DirectCredentials("gitlab-maven-3", "gitlab.com", username, password)
      )
    },
    csrConfiguration ~= (
      _.addRepositoryAuthentication("gitlab-maven-1", auth)
        .addRepositoryAuthentication("gitlab-maven-2", auth)
        .addRepositoryAuthentication("gitlab-maven-3", auth)
    ),
    updateClassifiers / csrConfiguration ~= (
      _.addRepositoryAuthentication("gitlab-maven-1", auth)
        .addRepositoryAuthentication("gitlab-maven-2", auth)
        .addRepositoryAuthentication("gitlab-maven-3", auth)
    )
  )
}
```

And here is what sbt-updates does
```
repositoryId=gitlab-maven-2

authentications= List(
  RepositoryAuthentication(None,Some(gitlab-maven-1),Some(gitlab.com),Private-Token,token,List()), 
  RepositoryAuthentication(None,Some(gitlab-maven-2),Some(gitlab.com),Private-Token,token,List()), 
  RepositoryAuthentication(None,Some(gitlab-maven-3),Some(gitlab.com),Private-Token,token,List()), 
  RepositoryAuthentication(Some(gitlab-maven-1),None,None,,,Vector((Private-Token,token))), 
  RepositoryAuthentication(Some(gitlab-maven-2),None,None,,,Vector((Private-Token,token))), 
  RepositoryAuthentication(Some(gitlab-maven-3),None,None,,,Vector((Private-Token,token))))

hostAuthentication=Some(RepositoryAuthentication(None,Some(gitlab-maven-1),Some(gitlab.com),Private-Token,token,List()))

connection.getRequestProperties={User-Agent=[Apache Ivy/2.3.0-sbt-fbc4f586aeeb1591710b14eb4f41b94880dcd745]}
```

the 
```
    credentials ++= creds.flatMap { case (username, password) =>
      List(
        new DirectCredentials("gitlab-maven-1", "gitlab.com", username, password),
        new DirectCredentials("gitlab-maven-2", "gitlab.com", username, password),
        new DirectCredentials("gitlab-maven-3", "gitlab.com", username, password)
      )
    },
```

breaks the behavior you dev-ed. So I removed it and it works. I'll have to test our CI pipelines to be sure it doesn't break anything.

**Comment by rtimush** [comment]
@AlixBa Thank you for testing! So, it seems that if both `credentials` and `csrConfiguration` are defined, sbt uses the latter, while `sbt-updates` prefers the former. #279 should make this more consistent.

**Comment by rtimush** [comment]
@L7R7 If sbt-updates uses the correct credentials, then most likely it cannot extract artifact versions from the server response. You can check the files that `sbt-updates` tries to download to see if they contain the correct versions (either in `maven-metadata.xml`, or as a directory listing matching [this](https://github.com/rtimush/sbt-updates/blob/66f38dbd238de5f4dbdbee2ed3c99d73fdee42c3/src/main/scala/com/timushev/sbt/updates/metadata/extractor/HtmlVersionExtractor.scala#L9) regexp).

**Comment by L7R7** [comment]
@rtimush thanks for the hint, I checked the files it tries to download and when I try to open them in my browser I get a 404. So it might not be a problem of sbt-updates, but with the way we're publishing the artifacts (which sounds weird to me, I thought we have everything we need to publish the package correctly)
