### ISSUE TITLE
Ignore Invalid Versions

### ISSUE THREAD

**Issue by rleibman** [rtimush/sbt-updates#242]
I get the following: 
[info]   com.google.apis:google-api-services-calendar : v3-rev411-1.25.0 -> InvalidVersion(v3-rev99-1.19.0)
Somebody at some point in the google thing created a v3-rev99 version, for some reason, dependencyUpdates thinks that this invalid version is higher than the current version, so I can't tell what the actual latest version is (yeah, argue with google about not using semver, but still, it does say "InvalidVersion").

**Comment by rtimush** [comment]
The reason was that both versions were considered invalid, and in this case no "smart" comparison logic were applied. I updated the code to allow such versions.

**Comment by rleibman** [comment]
Thanks for addressing this!
