### ISSUE TITLE
VersionEye Integration

### ISSUE THREAD

**Issue by reiz** [rtimush/sbt-updates#35]
Hi. I'm the dude behind VersionEye and recently we added Scala SBT support to our Service. VersionEye can monitor a build.sbt file on GitHub / Bitbucket and notify you about out-dated dependencies via email. Like you use a CI system to automate your tests, VersionEye is a Continuous Updating Service in the cloud. You can read more here: 

http://blog.versioneye.com/2014/09/15/scala-sbt-support/ 

For more complex builds we have native plugins. For example the [Maven Plugin] (github.com/versioneye/versioneye_maven_plugin) and the [Gradle Plugin](https://github.com/stempler/gradle-versioneye-plugin), which work against the [VersionEye API](https://www.versioneye.com/api/). 

I wonder if it would make sense to integrate the VersionEye API into this Plugin? Or is it out of scope and it would be a completely separate Plugin? I'm not sure. Your feedback is appreciated.

**Comment by sslavic** [comment]
I like sbt-updates support for failing a build on outdated dependencies in a project, as well as support for producing a report which can be used as build artifact. Both are good enough for me as a developer. Additionally when license related task(s) get added through https://github.com/rtimush/sbt-updates/issues/38 it will be great.

I'd still like to have project under VersionEye, a nice dashboard for collaboration, for team and management to use. Also I like VersionEye widgets/badge one can integrate to display status e.g. in readme.md (like build status).

It would be annoying if build would fail with sbt-updates while VersionEye displays project dependencies to be up-to-date or vice-versa, or if different licenses would be reported for same dependency by the two tools.

**Comment by reiz** [comment]
@sslavic @rtimush Now there is a [VersionEye-SBT-Plugin](https://github.com/versioneye/versioneye_sbt_plugin). It works similar to the [VersionEye-Maven-Plugin](https://github.com/versioneye/versioneye_maven_plugin). 

VersionEye is fetching the license and version information from different sources. Mainly from the Maven Central repository and JCenter. I'm not sure which other repositories are important for Scala developers. Just let me know so I can add them to the crawling framework.
