### ISSUE TITLE
No sbt-updates plugin for scala 2.13.x available 

### ISSUE THREAD

**Issue by a4z** [rtimush/sbt-updates#371]
Hi, 

I just wanted to add this plugin to a project.

But it seems sbt-updates is unavailable for scala 2.13.x, the latest scala 2 version.

Are there any plans to release a version for scala 2.13?

**Comment by SethTisue** [comment]
sbt 1 uses Scala 2.12 for all build definitions and plugins.

Your own code can use any version of Scala it wants — that's orthogonal.

**Comment by a4z** [comment]
I am not a scala expert, not even beginner, so I miss some details 
my sbt file says `ThisBuild / scalaVersion := "2.12.18"` 

I was under the impression that this is what my program uses, 
Since I never installed any scala, just sbt.
And if I update this to 2.13.12 some plugins could not be found.
The error message says it's looking for a download with 2.13.x in the name.

I guess I missed some information that average scala developers have?

**Comment by SethTisue** [comment]
https://scala-lang.org/community has suggestions on places to look for this kind of help
