### ISSUE TITLE
Ignore dependencies introduced by other plugins

### ISSUE THREAD

**Issue by travisbrown** [rtimush/sbt-updates#42]
I'm not sure this is possible, but it would be nice to ignore dependencies that other plugins add to `libraryDependencies`. For example, given this minimal `plugins.sbt` (which is currently up to date—1.0.1 is the latest sbt-scoverage):

```
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.0.1")

addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.1.7")
```

sbt-updates will report out of date dependencies:

```
[info]   org.scoverage:scalac-scoverage-plugin_2.10:provided  : 1.0.1  -> 1.0.2
[info]   org.scoverage:scalac-scoverage-runtime_2.10:provided : 1.0.1  -> 1.0.2
```

sbt-scoverage adds these to the project's `libraryDependencies` via [`projectSettings`](https://github.com/scoverage/sbt-scoverage/blob/53fd91900d71b2a4697f5f28a1d56c606fc90628/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L93).

I'm not sure whether there's any way to identify these dependencies as introduced by a plugin. Changing the order of lines in `plugins.sbt` has no effect.

**Comment by rtimush** [comment]
SBT tracks the source of a SettingKey:
```
> consoleProject
scala> attributes.entries.foreach(println)
...
setting(ScopedKey(Scope(Select(ProjectRef(file:/Users/roman/Workspaces/Scala/sbt-updates/,sbt-updates)),Global,Global,Global),libraryDependencies)) at LinePosition((scoverage.ScoverageSbtPlugin) ScoverageSbtPlugin.scala,93)
...
```
However, as far as I understand I'd have to evaluate the settings manually keeping track of the dependencies added on every step. It seems possible but not trivial.

**Comment by dwijnand** [comment]
I think I bear good news!

In the process of looking at this issue I found out that for library dependencies in particular this might be very accessible: there is a `dependencyPositions` which is a `TaskKey[Map[ModuleID, SourcePosition]]`!

https://github.com/sbt/sbt/blob/v1.1.4/main/src/main/scala/sbt/Keys.scala#L356

With regards to compatibility, it's there as of sbt 0.13.16 (https://github.com/sbt/sbt/pull/1491).

**Comment by rtimush** [comment]
This looks very useful, thank you!
