### ISSUE TITLE
Support for private/authenticated repositories/resolvers?

### ISSUE THREAD

**Issue by agemooij** [rtimush/sbt-updates#45]
Does the plugin also visit non-standard, private or authenticated repositories?

We have some project-internal libraries that we publish to a private Artifactory instance that requires authentication. The repository has been added to the SBT `resolvers` setting and the relevant credentials has been added to the SBT `credentials` setting. Dependency resolution works as expected.

Unfortunately the `dependencyUpdates` command does not seem to visit this repository or report outdated internal library dependencies. Am I doing something wrong or is this not supported?

**Comment by rtimush** [comment]
Thanks for reporting. It is not supported yet, but I will try to implement a fix this week.

**Comment by agemooij** [comment]
Thanks! 
Let me know if you need more information or feedback. We can also test-drive snapshots if that helps.

**Comment by sattvik** [comment]
I have submitted a PR, #52, that solves this issue for us with our Nexus instance.  Whenever credentials are defined for a particular repository, it attempts to use basic auth.  It won't work for cases where some other type of authentication is required.

**Comment by agemooij** [comment]
@sattvik awesome! 

Hopefully I'll have some time this week to test your version. We use a private Artifactory instance that indeed uses basic auth (over https) so this should work for us and it would be very welcome.

**Comment by agemooij** [comment]
I can confirm that this works! Thanks a lot!

I tested against `0.1.9-6-g5a7705c` and found out of date internal libraries. A new stable release would be very much appreciated.
