### ISSUE TITLE
sadness :-)

### ISSUE THREAD

**Issue by mtk** [rtimush/sbt-updates#49]
https://dl.bintray.com/sbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.10/sbt_0.13/ says where is 0.1.9?

**Comment by hepin1989** [comment]
could not found 0.1.3 too.

**Comment by agemooij** [comment]
0.1.9 is indeed missing.

**Comment by rtimush** [comment]
For some reason I thought that artifactory -> bintray migration affects snapshot versions only. Will fix.

**Comment by rtimush** [comment]
Fixed, thanks for reporting
