### ISSUE TITLE
sbt-updates is not compatible with scala 2.11.x?

### ISSUE THREAD

**Issue by jpzk** [rtimush/sbt-updates#50]
Hi guys,

I tried to use sbt-updates with Scala 2.11.x? It couldnt resolve the dependency, so I assumed it is not in the repository, for that Scala version. I checked manually, and there is no built for these versions. Is 2.11.X support planned?

Kind regards,
jpzk

**Comment by wookietreiber** [comment]
Might be related to / duplicate of #49.

**Comment by rtimush** [comment]
Try 0.1.8 for now

**Comment by jpzk** [comment]
It works, thank you :)
