### ISSUE TITLE
Hangs on a jboss remoting dependency

### ISSUE THREAD

**Issue by gpgekko** [rtimush/sbt-updates#53]
For some reason, sbt-updates seems to consistently hang on the following dependency:

    "org.jboss.remoting" % "jboss-remoting" % "4.0.9.Final"

I've left it running a few times and it will timeout after a hour or so. I've tried removing all other dependencies, but the only way to resolve things is to remove it. So now I just comment it out before running the `dependencyUpdates` task and put it back after, but that is a bit of a hassle, so I hope you can figure this out!

**Comment by rtimush** [comment]
Do you still have this problem? If yes can you please share a list of configured resolvers? I tried with the default ones and it works:
```
[info]   org.jboss.remoting:jboss-remoting : 4.0.9.Final -> 4.0.19.Final
```

**Comment by gpgekko** [comment]
I can't reproduce it anymore. Looking at the [version releases](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.jboss.remoting%22%20AND%20a%3A%22jboss-remoting%22), it seems there have been releases since the last time I had this. Maybe one of those older versions has a name that didn't play well with the system?

Either way, I'll close this since it is no longer reproducible (and hopefully just a fluke).

**Comment by rtimush** [comment]
Bad versions would likely cause crashes, not hangs. It is more likely that there were some network problems. Anyway, good to know that it is not reproducible now.
