### ISSUE TITLE
Update the README to reflect 0.1.10 as the latest version

### ISSUE THREAD

**Issue by agemooij** [rtimush/sbt-updates#54]
I would send in a PR for this minor change but I'm not sure what the deal is with the section on snapshot versions since the latest snapshot version (0.1.9-6-g5a7705c) seems to be older than the latest version (0.1.10).

**Comment by rtimush** [comment]
Thanks for fixing the readme. As for the snapshot version — this happened because the release tag was on the head git commit, and therefore there was no newer snapshot release. Probably it is not a big issue.
