### ISSUE TITLE
Support non-numerical versions

### ISSUE THREAD

**Issue by jedesah** [rtimush/sbt-updates#59]
Many libraries now use the `a` suffix in order to distinguish between artifacts built with `scalaz` `7.1.x` and `7.2.x`. So for instance `http4s` publishes both a `0.13.2` and `0.13.2a`.

Currently, `sbt-updates` reports `0.13.2` as being an update over `0.13.2a` which is somewhat surprising given typical `String` ordering. To be fair, the ideal behavior would probably to have special support for this convention and not report either as an upgrade to the other.

Perhaps ignoring extra characters is the way to go. I had a quick look at the implementation which only deals with `Long`, so I am not too sure exactly what is happening in order for `0.13.2a` to be reported as a previous version to `0.13.2a`.

I think support for just this `a` convention would be great but perhaps there is a more general solution as `specs2` often add suffixes to its version in order to cross-build with different version of `scalacheck` or `scalaz`.

**Comment by laughedelic** [comment]
What does this suffix mean? I think this doesn't fit in the semantic versioning schema.

**Comment by hosamaly** [comment]
If suffixes are to be considered, then it would make sense to consider them to have a lower value than versions without suffixes, e.g. `0.13.2-M5` or `0.13.2rc`.

**Comment by rtimush** [comment]
Non-numerical versions are supported, but `0.13.2a` is indeed considered a pre-release version to `0.13.2`. I don't see any way to generically support custom versioning schemes like this `a` suffix for different scalaz versions. I can allow implementing custom version comparison strategies  as a part of your own build script (planned), and provide a few pre-defined ones like the one used by http4s.

**Comment by rtimush** [comment]
All issues like this are tracked by #19
