### ISSUE TITLE
Exclude Dependencies by Classifier

### ISSUE THREAD

**Issue by omervk** [rtimush/sbt-updates#82]
I have a project that ultimately runs on a hosted service which provides jars in the classpath at runtime. This means that:

1. I use the classifier `provided`, and;
2. I can't upgrade these dependencies unless the hosting service does.

I would love to see a feature that lets me filter by classifier so I can skip these dependencies in the report.

**Comment by rtimush** [comment]
Sounds reasonable to me. You can already achieve what you want using `dependencyUpdatesFilter`, but there is no ready-to-use utility to filter by configuration so you have to subclass `sbt.ModuleFilter`:
```scala
dependencyUpdatesFilter := new sbt.ModuleFilter {
  override def apply(a: ModuleID) = a.configurations.forall(_ != "provided")
}
```

**Comment by omervk** [comment]
That's an interesting solution, but implementing it in my sbt file fails to filter out any dependency. I might be using it wrong. Could you please clarify where this piece of code needs to be written?

**Comment by rtimush** [comment]
Do you have your dependencies just in the `provided` configuration, or it is something like `provided,test`?

**Comment by omervk** [comment]
You're right, my dependencies do look like `provided,test`. I changed your code to accommodate for that and ran that and it didn't work:
```
dependencyUpdatesFilter := new ModuleFilter {
  override def apply(a: ModuleID) = a.configurations.forall(_.split(',').contains("provided"))
}
```
Trying further, it also looks like using the `dependencyUpdatesFilter -= moduleFilter(...)` syntax doesn't work either for any dependency I have so... o_O

**Comment by rtimush** [comment]
Sorry, somehow I didn't see your comment. I just tested it locally and the following code worked for me:
```scala
dependencyUpdatesFilter := ((a: ModuleID) => !a.configurations.exists(_.split(",").contains("provided")))
```
If it is still not working for you, can you share you build file please?

**Comment by omervk** [comment]
Unfortunately, I won't be able to pursue this issue as I've left the company in whose build this was happening and no longer have access to it. I'll close the issue. Hopefully this was a rare case.
