### ISSUE TITLE
Output contains invisible non-space trailing characters

### ISSUE THREAD

**Issue by leesah** [rtimush/sbt-updates#83]
I am trying to write a script to automatically step the version of a certain dependency, the first step of which is to extract the latest version of it with sbt-updates:

    $ sbt -batch dependencyUpdates | awk -F'\\s+->\\s+' '/com.example:example-artifact/ {print $NF}'
    1.3

Which looks fine until I try to trim the trailing whitespaces:

    $ sbt -batch dependencyUpdates | awk -F'\\s+->\\s+' '/com.example:example-artifact/ {print $NF}' | sed 's/[^0-9]*$/x/g'
    1.3               ^[[2;1;1;112;112;1;0x

This is quite unfriendly when scripting. Could there be a cleaner output?

**Comment by rtimush** [comment]
Hi.
Have you considered `depencencyUpdatesReport` task? It writes the report to a text file and I think there should be no special characters.
Another option is to write your automation as an SBT task and get the updates data from `dependencyUpdatesData`

**Comment by leesah** [comment]
Then this can be discussed in #84, I guess. I'm closing this issue.
