### ISSUE TITLE
sbt-updates hangs frequently in sbt 1.0

### ISSUE THREAD

**Issue by tpolecat** [rtimush/sbt-updates#85]
Hi, I absolutely love sbt-updates. It's one of the only things associated with sbt that brings me joy. So thanks for your work on it.

So ... when [re]loading our project we automatically run `dependencyUpdates` and have noticed that maybe 10% of the time it hangs after completing the report, with high CPU usage. We have to ^Z and `kill -9` to stop sbt. I don't know if it's an issue with sbt-updates or the underlying machinery in sbt but I thought I would start here. Unfortunately it's nondeterministic. 

The project in question is [here](https://github.com/gemini-hlsw/gem) if you'd like to try it. Just start it up and do `reload` a bunch of times.

**Comment by rtimush** [comment]
Happy to hear that you find sbt-updates so useful!
I think I identified the issue, can you please try version `0.3.4-2+gd4c4ec6` from `Resolver.bintrayIvyRepo("rtimush", "sbt-plugin-snapshots")`?

**Comment by tpolecat** [comment]
Yep, I'll give it a try. Thanks!

**Comment by tpolecat** [comment]
So far so good. I'll merge that and see what the ream reports.

**Comment by rtimush** [comment]
Hi @tpolecat. Have you our the team experienced any hangs after this fix? If not, I will release a new version.

**Comment by tpolecat** [comment]
We have not had any problems as far as I know.

**Comment by rtimush** [comment]
Fixed in 0.3.4
