### ISSUE TITLE
Post dependency updates report to Slack

### ISSUE THREAD

**Issue by mwz** [rtimush/sbt-updates#88]
I run the `dependencyUpdates` task as a part of an sbt-release process in my CI builds, but I never tend to check the output of successful builds and it's easy to forget to check for updates manually.

It would be awesome to have a Slack webhook integration so the plugin can send me a gentle reminder with the report if there are any libraries to update. ...and honestly, I wouldn't mind getting the same report multiple times a day - it would probably encourage me even more to update, because from practice I can tell that the longer you wait and the more versions you need to jump over the more effort it takes to update... 😄

Happy to contribute if other people would also find this useful.

**Comment by rtimush** [comment]
The Slack integration itself probably shouldn't be part of this plugin, as there are already various options to send slack notifications from either sbt or CI tools. However if something is missing in `sbt-updates` that would simplify integration, a PR would be very welcome.
