### ISSUE TITLE
`sbt dependencyUpdates` doesn't work if plugin installed globally

### ISSUE THREAD

**Issue by akauppi** [rtimush/sbt-updates#89]
I like the idea of `sbt-update` and have started using it.

However, there's strange behaviour observed. Adding the plugin to the global file is not enough (I have tried both `plugings.sbt` and the `sbt-updates.sbt` mentioned in the README). In order to have `sbt dependencyUpdates` to work on a given project, I first need to "visit" the plugin file locally. After that it works.

ie..

```
$ more ~/.sbt/1.0/plugins/plugins.sbt 
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")

addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.4")
```

```
$ sbt depedencyUpdates
[info] Loading settings from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/asko/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/asko/Git/foo/project
[info] Loading settings from build.sbt ...
[info] Set current project to foo (in build file:/Users/asko/Git/foo/)
[error] Not a valid command: depedencyUpdates
[error] Not a valid project ID: depedencyUpdates
[error] Expected ':'
[error] Not a valid key: depedencyUpdates (similar: dependencyStats, dependencyDot, dependencyClasspath)
[error] depedencyUpdates
[error]                 ^
```

But, if I

```
$ cp ~/.sbt/1.0/plugins/plugins.sbt project/aaa.sbt
```

..then things work. After that, I can remove `project/aaa.sbt` and things continue to work.

I have some idea what may be going on here, but thought to report.

System:
- macOS 10.13.3

**Comment by agemooij** [comment]
@akauppi It looks like you have a typo in your original call, e.g. you typed `sbt depedencyUpdates`, without the "n".

FYI I have used this plugin for years as a global plugin without any of the problems described so I think this is a simple user error instead of a bug.

**Comment by akauppi** [comment]
Oops, bad day.
